project:
  type: website
  output-dir: docs

website:
  title: "🍲 GutHub"
  repo-url: "https://github.com/cascadiarconf-gh-workshops/GutHub"
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: template-recipe.qmd
        text: "Template Recipe"
        
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
