name: Recipe Validation

on:
  pull_request:
    paths:
      - "recipes/*.md"

jobs:
  new-recipe-added:
    name: "Recipe Validation: New recipe added?"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for a new recipe .md file
        run: |
          pip install --upgrade pip
          python .github/scripts/check_new_md.py

  yaml-customized:
    name: "Recipe Validation: YAML customized?"
    runs-on: ubuntu-latest
    needs: new-recipe-added
    if: needs.new-recipe-added.result == 'success'
    steps:
      - uses: actions/checkout@v4
      - name: Validate YAML
        run: |
          pip install --upgrade pip
          python .github/scripts/validate_yaml_fields.py

  image-exists:
    name: "Recipe Validation: Image exists & tag matches?"
    runs-on: ubuntu-latest
    needs: new-recipe-added
    if: needs.new-recipe-added.result == 'success'
    steps:
      - uses: actions/checkout@v4
      - name: Validate image
        run: |
          pip install --upgrade pip
          python .github/scripts/validate_image_and_tag.py

  sections-customized:
    name: "Recipe Validation: Sections customized?"
    runs-on: ubuntu-latest
    needs: new-recipe-added
    if: needs.new-recipe-added.result == 'success'
    steps:
      - uses: actions/checkout@v4
      - name: Validate sections
        run: |
          pip install --upgrade pip
          python .github/scripts/validate_sections.py
