name: Recipe Submission Validation

on:
  pull_request:
    paths:
      - "recipes/*.md"

jobs:
  check-new-md-file:
    name: "Check: PR Adds New Recipe Markdown File"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure PR adds a new .md file in recipes/
        run: |
          pip install --upgrade pip
          python .github/scripts/check_new_md.py

  check-yaml-fields:
    name: "Check: All YAML Fields Customized"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate all YAML fields are changed from template
        run: |
          pip install --upgrade pip
          python .github/scripts/validate_yaml_fields.py

  check-image-and-tag:
    name: "Check: Image Exists and Img Tag Matches"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate image path, file, and <img> tag
        run: |
          pip install --upgrade pip
          python .github/scripts/validate_image_and_tag.py

  check-sections-changed:
    name: "Check: Recipe Sections Are Customized"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate Ingredients, Instructions, and Suggestions sections
        run: |
          pip install --upgrade pip
          python .github/scripts/validate_sections.py
