name: Validate Recipe Submissions

on:
  pull_request:
    paths:
      - "recipes/*.md"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Run recipe validator
        run: python .github/scripts/validate_recipe.py
        continue-on-error: true
